CREATE TYPE  name as Object(
    firstname varchar2(100),
    lastname varchar2(100)
);

CREATE TYPE address as Object(
    street varchar2(100),
    city varchar2(100),
    zip_code varchar2(100)
);

CREATE TYPE phone_list AS
TABLE OF NUMBER

CREATE TYPE items AS
TABLE OF NUMBER

CREATE TABLE users(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name NAME not null,
    email varchar2(100) not null UNIQUE,
    password varchar2(255) not null,
    address ADDRESS,
    phone_numbers PHONE_LIST,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY(id)
)
NESTED TABLE phone_numbers STORE AS phone_nested;

CREATE TABLE products(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name varchar2(100) not null,
    description varchar2(255),
    brand varchar2(255),
    price NUMBER(8,2) not null,
    stock NUMBER(38) not null,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE products
ADD CONSTRAINT check_positive_price CHECK(price > 0);

CREATE TABLE options(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name varchar2(100) not null,
    product_id NUMBER not null,
    PRIMARY KEY(id),
    FOREIGN KEY(product_id) REFERENCES products(id)
    ON DELETE CASCADE
);


CREATE TABLE option_values(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    option_id NUMBER not null,
    name varchar2(100) not null,
    PRIMARY KEY(id),
    FOREIGN KEY(option_id) REFERENCES options(id)
    ON DELETE CASCADE
);

CREATE TABLE variants(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER,
    description varchar2(255),
    price NUMBER (8,2),
    stock NUMBER,
    stock_threshold NUMBER,
    media_id varchar2(255),
    PRIMARY KEY(id),
    FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
);

ALTER TABLE variants 
    MODIFY price NUMBER(18,2);

CREATE TABLE option_value_variant(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    option_value_id NUMBER,
    variant_id NUMBER,
    PRIMARY KEY(id),
    FOREIGN KEY (option_value_id) REFERENCES option_values(id),
    FOREIGN KEY (variant_id) REFERENCES variants(id) ON DELETE CASCADE
);

CREATE TABLE payment_type(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar2(100) NOT NULL;
);

CREATE TABLE cart
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    client_id NUMBER NOT NULL,
    product_items ITEMS,
    PRIMARY KEY(id),
    FOREIGN KEY(client_id) REFERENCES users(id)
)
NESTED TABLE product_items STORE AS product_items_nested;

CREATE TABLE invoices
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    client_id NUMBER NOT NULL,
    total_amount NUMBER(18,2) NOT NULL,
    payment_type_id NUMBER NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(client_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(payment_type_id) REFERENCES payment_type(id)
);

CREATE TABLE invoice_details
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    invoice_id NUMBER,
    variant_id NUMBER,
    quantity NUMBER(18,2),
    PRIMARY KEY(id),
    FOREIGN KEY(invoice_id) REFERENCES invoices(id),
    FOREIGN KEY(variant_id) REFERENCES variants(id)
);

-- users
INSERT INTO users (name, email, password, address, phone_numbers, created_at, updated_at)VALUES
(Name('Visar', 'Buza'), 'visar.buza7@gmail.com','123456',Address('Rr. Nena Tereze','Prishtine','10000'),PHONE_LIST(045292300,044292198),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


-- products
INSERT INTO products(name, description, brand, price, stock, created_at, updated_at) VALUES
('Sweater','Lorem ipsum','Gucci',15,30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO products(name, description, brand, price, stock, created_at, updated_at) VALUES
('T Shirt','Lorem ipsum','Adiddas', 45,30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO products(name, description, brand, price, stock, created_at, updated_at) VALUES
('Jeans','High quality denim','Diesel',70,40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO products(name, description, brand, price, stock, created_at, updated_at) VALUES 
('Jacket', 'Lorem ipsum', 'Versace', 100,    40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



INSERT INTO options(name, product_id) VALUES ('Size', 1);

INSERT INTO options(name, product_id) VALUES ('Size',2);

INSERT INTO options(name, product_id) VALUES ('Color',2);

INSERT INTO options(name, product_id) VALUES ('Size',3);

INSERT INTO options(name, product_id) VALUES ('Fit',3);

INSERT INTO options(name, product_id) VALUES('Size',4);



INSERT INTO option_values(name, option_id)VALUES ('S',1);

INSERT INTO option_values(name, option_id) VALUES ('M',1);

INSERT INTO option_values(name, option_id)VALUES ('L',1);

INSERT INTO option_values(name, option_id)VALUES ('S',2);

INSERT INTO option_values(name, option_id) VALUES ('M',2);

INSERT INTO option_values(name, option_id)VALUES ('L',2);

INSERT INTO option_values(name, option_id) VALUES ('XXL', 2);

INSERT INTO option_values(name, option_id)VALUES ('Black',2);

INSERT INTO option_values(name, option_id) VALUES ('White',2);

INSERT INTO option_values(name, option_id)VALUES ('Gray',2);

INSERT INTO option_values(name, option_id)VALUES ('30',3);

INSERT INTO option_values(name, option_id) VALUES ('32',3);

INSERT INTO option_values(name, option_id)VALUES ('34',3);

INSERT INTO option_values(name, option_id)VALUES ('Regular',3);

INSERT INTO option_values(name, option_id) VALUES ('Slim',3);

INSERT INTO option_values(name, option_id)VALUES ('Skinny',3);

INSERT INTO option_values(name, option_id)VALUES ('S',4);

INSERT INTO option_values(name, option_id) VALUES ('M',4);

INSERT INTO option_values(name, option_id)VALUES ('L',4);

INSERT INTO option_values(name, option_id) VALUES ('XXL', 4);



INSERT INTO payment_type (name) VALUES ('PayPal');

INSERT INTO payment_type (name) VALUES ('Apple Pay');

INSERT INTO payment_type (name) VALUES ('VISA');

INSERT INTO payment_type (name) VALUES ('Master Card');

INSERT INTO payment_type (name) VALUES ('Maestro');



